### ISSUE TITLE
refactorizare cod

### ISSUE THREAD

**Issue by HoreaOros** [Lemnus/AllConverter#2]
codul trebuie refactorizat pentru a fi mai usor de urmarit. functii mai scurte cu nume clare din care sa rezulte ce fac. 
fiecare functie sa fie responsabila de un task mai mic

**Comment by Lemnus** [comment]
Chiar dacă sunt de acord cu faptul ca programul este greu de urmărit, nu vad nicio modalitate de a schimba asta fără a face modificări complicate; cum programul face deja tot ce se cere și nu va avea nevoie de modificări ulterioare, as prefera sa evit rescrierea (și implicit reînvățarea) programului
