### ISSUE TITLE
Exponentiere eficienta

### ISSUE THREAD

**Issue by HoreaOros** [Lemnus/AllConverter#4]
https://github.com/Lemnus/AllConverter/blob/01282f3bb84fe04932ee35d7045abb6a8ccaa48c/TheAllConverter/Program.cs#L365

Trebuie schimbata functia de exponentiere cu o varianta eficienta. (doar ca exercitiu "scolaresc" :wink:).

**Comment by HoreaOros** [comment]
Exponentierea nu e facuta eficient.

**Comment by Lemnus** [comment]
https://en.wikipedia.org/wiki/Addition-chain_exponentiation 
La asta va asteptati?

**Comment by HoreaOros** [comment]
Pentru inceput ar fi suficient exponentierea binara (recursiv si nerecursiv). https://en.wikipedia.org/wiki/Exponentiation_by_squaring

Daca vrei sa mergi mai departe poti studia si alte metode mai sofisticate.

**Comment by Lemnus** [comment]
Poate nu am inteles eu dar nu asta face AltPowerUp(adaugata in ultimul commit)?

**Comment by HoreaOros** [comment]
Ba da. Probabil ca mi-a scapat funcția respectivă.
